<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>解約時信託財産留保額</description>
   <name>解約時信託財産留保額</name>
   <tag></tag>
   <elementGuidId>96d9e0e7-d93a-45a9-8d94-dde6a064fd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'解約時信託財産留保額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'解約時信託財産留保額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
