<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>解約時手数料率</description>
   <name>解約時手数料率</name>
   <tag></tag>
   <elementGuidId>397af087-5c36-4654-84ad-6d081a182981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'解約時手数料率')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'解約時手数料率')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
