<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>購入時信託財産留保額</description>
   <name>購入時信託財産留保額</name>
   <tag></tag>
   <elementGuidId>7fce221f-78f4-478c-a67d-83782d472e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'購入時信託財産留保額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'購入時信託財産留保額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
